"""
Tests for the bank statement parsers generated by the AI agent.
"""

import pytest
import pandas as pd
from pathlib import Path


def test_icici_parser():
    """Test the ICICI bank statement parser"""

    try:
        from custom_parsers.icici_parser import parse
    except ImportError:
        pytest.skip("ICICI parser not yet generated")
    
    # Get paths
    sample_pdf = Path("data/icici/icici sample.pdf")
    expected_csv = Path("data/icici/result.csv")
    
    # Skip if files don't exist
    if not (sample_pdf.exists() and expected_csv.exists()):
        pytest.skip("Sample PDF or expected CSV not found")
    
    # Parse PDF
    result_df = parse(sample_pdf)
    print('--- Parsed DataFrame ---')
    print(result_df.head())

    # Load expected result
    expected_df = pd.read_csv(expected_csv)
    print('--- Expected DataFrame ---')
    print(expected_df.head())
    
    # Compare results
    assert result_df.equals(expected_df), "Parser output does not match expected CSV"