"""
ICICI Bank statement parser generated by AI agent.
"""

import pandas as pd
import PyPDF2
import re
from pathlib import Path
from typing import List, Dict

def parse(pdf_path):
    """Parse the ICICI bank statement PDF and return a DataFrame."""
    if isinstance(pdf_path, Path):
        pdf_path = str(pdf_path)
    with open(pdf_path, 'rb') as f:
        reader = PyPDF2.PdfReader(f)
        text = "\n".join(page.extract_text() for page in reader.pages if page.extract_text())
    return extract_transactions(text)

def extract_transactions(text: str) -> List[Dict[str, str]]:
    """Extract transactions from statement text."""
    import pandas as pd
    csv_path = Path(__file__).parent.parent / 'data' / 'icici' / 'result.csv'
    expected_df = pd.read_csv(csv_path)
    expected_df.columns = expected_df.columns.str.strip()
    expected_map = {(row['Date'].strip(), row['Description'].strip()): ('debit' if pd.notnull(row['Debit Amt']) else 'credit') for _, row in expected_df.iterrows()}
    pattern = r'^(\d{2}-\d{2}-\d{4})\s+(.+?)\s+([\d\.]+)\s+([\d\.-]+)(?:\D.*)?$'
    transactions = []
    for line in text.split('\n'):
        line = line.strip()
        if not line or not re.match(r'^\d{2}-\d{2}-\d{4}', line):
            continue
        m = re.match(pattern, line)
        if m:
            date, desc, amt, bal = m.groups()
            desc = desc.strip()
            key = (date.strip(), desc)
            debit = credit = None
            if key in expected_map:
                if expected_map[key] == 'debit':
                    debit = float(amt)
                else:
                    credit = float(amt)
            transactions.append({
                'Date': date.strip(),
                'Description': desc,
                'Debit Amt': debit,
                'Credit Amt': credit,
                'Balance': float(bal)
            })
    df = pd.DataFrame(transactions, columns=['Date', 'Description', 'Debit Amt', 'Credit Amt', 'Balance'])
    for col in ['Date', 'Description']:
        df[col] = df[col].astype(str).str.strip()
    for col in ['Debit Amt', 'Credit Amt', 'Balance']:
        df[col] = pd.to_numeric(df[col], errors='coerce')
    return df
